version: '3' # vs mais atual
networks:
  nlw-network:
    driver: bridge
services:

  app:
    build: .
    container_name: config_img
    restart: always
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    # command: nvidia-smi
    ports:
      - "3333:3333"
    volumes:
      - .:/app