version: '3' # vs mais atual
networks:
  nlw-network:
    driver: bridge
services:

  app:
    build: .
    container_name: config_img
    restart: always
    tty: true
    ports:
      - "3333:3333"
    volumes:
      - .:/app